### ISSUE TITLE
doesnt build on windows

### ISSUE THREAD

**Issue by ravi005e** [amiya-pattnaik/webdriverIO-with-jasmineBDD#1]
C:\Users\rshanker\git\webdriverIO-with-jasmineBDD>npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated connect@2.4.6: connect 2.x series is deprecated
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> v8-profiler@5.7.0 preinstall C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-profiler
> node -e 'process.exit(0)'

> v8-debug@1.0.1 preinstall C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug
> node -e 'process.exit(0)'

> heapdump@0.3.9 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump
> node-gyp rebuild

C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
     Creating library C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump\build\Release\addon.lib and obje
  ct C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump\build\Release\addon.exp
  Generating code
  Finished generating code
  addon.vcxproj -> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump\build\Release\\addon.node
  addon.vcxproj -> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\heapdump\build\Release\addon.pdb (Full PDB)

> appium-chromedriver@3.5.2 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.37' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.37/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\rshanker\AppData\Local\Temp\201845-9968-1r5ekkr.p2li\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\rshanker\AppData\Local\Temp\201845-9968-1r5ekkr.p2li\chromedriver_win32.zip to C:\Users\rshanker\AppData\Local\Temp\201845-9968-1r5ekkr.p2li\chromedriver_win32
info Chromedriver Install Creating C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\rshanker\AppData\Local\Temp\201845-9968-1r5ekkr.p2li\chromedriver_win32\chromedriver.exe...
info Chromedriver Install Writing to C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe...
info Chromedriver Install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successfully put in place

> appium-selendroid-driver@1.7.0 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_161
info Selendroid Ensuring C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from http://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
info Selendroid Writing binary content to C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download
info Selendroid Copying manifest and apk to C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-selendroid-driver\selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

> appium-windows-driver@1.1.0 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\appium\node_modules\appium-windows-driver
> node install-npm.js

info WinAppDriver You must use WinAppDriver version 1.0
info WinAppDriver Verifying WinAppDriver version 1.0 is installed via comparing the checksum.
info WinAppDriver WinAppDriver.exe doesn't exist at the correct version 1.0, setting up
WARNING: You are not running as an administrator so WinAppDriver cannot be installed for you; please reinstall as admin
WinAppDriver was not installed; please check your system and re-run npm install if you need WinAppDriver

> fibers@1.0.15 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers
> node build.js || nodejs build.js

C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
  win_delay_load_hook.cc
..\src\coroutine.cc(138): warning C4552: '!': operator has no effect; expected operator with side-effect [C:\Users\rshanker\git\webdriverIO-with-j
asmineBDD\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(122): warning C4996: 'v8::String::NewFromOneByte': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\nod
e_modules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(2683): note: see declaration of 'v8::String::NewFromOneByte'
..\src\fibers.cc(126): warning C4996: 'v8::String::NewFromOneByte': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\nod
e_modules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(2683): note: see declaration of 'v8::String::NewFromOneByte'
..\src\fibers.cc(433): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node
_modules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(3847): note: see declaration of 'v8::Function::NewInstance'
..\src\fibers.cc(737): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of data [C:\Users\rshanker\git\webdrive
rIO-with-jasmineBDD\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(741): warning C4244: '=': conversion from 'double' to 'std::size_t', possible loss of data [C:\Users\rshanker\git\webdriverIO-wit
h-jasmineBDD\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(741): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modul
es\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\fibers.cc(748): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of data [C:\Users\rshanker\git\webdrive
rIO-with-jasmineBDD\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(793): warning C4996: 'v8::Object::SetAccessor': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_m
odules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(3185): note: see declaration of 'v8::Object::SetAccessor'
..\src\fibers.cc(794): warning C4996: 'v8::Object::SetAccessor': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_m
odules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(3185): note: see declaration of 'v8::Object::SetAccessor'
..\src\fibers.cc(795): warning C4996: 'v8::Object::SetAccessor': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_m
odules\fibers\build\fibers.vcxproj]
  c:\users\rshanker\.node-gyp\8.11.1\include\node\v8.h(3185): note: see declaration of 'v8::Object::SetAccessor'
  coro.c
     Creating library C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers\build\Release\fibers.lib and object C:\Users\rshanker\
  git\webdriverIO-with-jasmineBDD\node_modules\fibers\build\Release\fibers.exp
  Generating code
  Finished generating code
  fibers.vcxproj -> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers\build\Release\\fibers.node
  fibers.vcxproj -> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers\build\Release\fibers.pdb (Full PDB)
Installed in `C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\fibers\bin\win32-x64-57\fibers.node`

> phantomjs-prebuilt@2.1.16 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\rshanker\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\rshanker\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1525573587354\phantomjs-2.1.1-windows -> C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
> v8-debug@1.0.1 install C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  debug.cc
  InjectedScriptHost.cc
  win_delay_load_hook.cc
..\src\debug.cc(41): warning C4996: 'v8::Debug::Call': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-
debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(195): note: see declaration of 'v8::Debug::Call'
..\src\debug.cc(52): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_
modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\debug.cc(57): warning C4996: 'v8::Debug::SendCommand': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modu
les\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(172): note: see declaration of 'v8::Debug::SendCommand'
..\src\debug.cc(78): error C2039: 'GetMirror': is not a member of 'v8::Debug' [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-d
ebug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(26): note: see declaration of 'v8::Debug'
..\src\debug.cc(78): error C3861: 'GetMirror': identifier not found [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug\build
\debug.vcxproj]
..\src\debug.cc(71): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_
modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\debug.cc(80): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_
modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\InjectedScriptHost.cc(99): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_
modules\v8-debug\build\debug.vcxproj]
  c:\users\rshanker\git\webdriverio-with-jasminebdd\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\rshanker\\git\\webdriverIO-with-jasmineBDD\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\rshanker\\git\\webdriverIO-with-jasmineBDD\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rshanker\\git\\webdriverIO-with-jasmineBDD\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-jasmineBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64' (1)
npm WARN grunt-webdriver@2.0.3 requires a peer of grunt@^1.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN webdriverIO-with-jasmineBDD@1.1.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rshanker\AppData\Roaming\npm-cache\_logs\2018-05-06T02_26_41_865Z-debug.log

**Comment by amiya-pattnaik** [comment]
I guess it seems to be specific to windows on the latest node version. You can try with node 6.10 version is a pretty stable version and check. for the latest node LTS version Please try install `node-gyp` which is native addon build tool.  refer to this link for installation on windows .. https://www.npmjs.com/package/node-gyp

Once build tool is installed properly you should be able to proceed.
