### ISSUE TITLE
getting below issue while running test

### ISSUE THREAD

**Issue by SawantR** [amiya-pattnaik/webdriverIO-with-jasmineBDD#3]
webdriverIO-with-jasmineBDD-master\node_modules\.bin\wdio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverIO-with-jasmineBDD@2.0.0 test: `node node_modules/.bin/wdio ./test/config/suite.jasmine.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverIO-with-jasmineBDD@2.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rohansa\AppData\Roaming\npm-cache\_logs\2019-04-05T07_13_34_350Z-debug.log

**Comment by amiya-pattnaik** [comment]
It seems to be issues with the windows OS build tool. Please fix your os specific build tool.
You can refer to the previous issue No,#1 in the closed state

**Comment by Alek5andr** [comment]
The same issue.
Don't know what to do more. Tried to update from Node.JS 8.12.0 to 11.0.0. NPM is also updated to 6.4.1.
What's the root cause - unknown.

**Comment by amiya-pattnaik** [comment]
Can you please mention what is the issue you are getting? send the snap shot.

    On Thursday, 18 July, 2019, 07:19:00 am GMT-5, Alek5andr <notifications@github.com> wrote:  
 
 
The same issue.
Don't know what to do more. Tried to update from Node.JS 8.12.0 to 11.0.0. NPM is also updated to 6.4.1.
What's the root cause - unknown.

**Comment by Alek5andr** [comment]
@amiya-pattnaik,

There is the error:
`> webdriverIO-with-jasmineBDD@2.0.0 test C:\Users\38811250338\WebstormProjects\webdriverIO-with-jasmineBDD
> node node_modules/.bin/wdio ./test/config/suite.jasmine.conf.js

C:\Users\38811250338\WebstormProjects\webdriverIO-with-jasmineBDD\node_modules\.bin\wdio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1`

By the way, I tried the source code on 2 machines, where:
- Windows 10
- Node.JS 11.0.0
- NPM 6.4.1

**Comment by amiya-pattnaik** [comment]
it seems to be your operating system is not loading the modules. It seems to be NPM module loader is not able to load. try NPM version 6.10 or 8.10 etc. and let me know

    On Friday, 19 July, 2019, 01:50:59 am GMT-5, Alek5andr <notifications@github.com> wrote:  
 
 
@amiya-pattnaik,

There is the error:
`> webdriverIO-with-jasmineBDD@2.0.0 test C:\Users\38811250338\WebstormProjects\webdriverIO-with-jasmineBDD


node node_modules/.bin/wdio ./test/config/suite.jasmine.conf.js


C:\Users\38811250338\WebstormProjects\webdriverIO-with-jasmineBDD\node_modules.bin\wdio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
^^^^^^^

SyntaxError: missing ) after argument list
at new Script (vm.js:80:7)
at createScript (vm.js:264:10)
at Object.runInThisContext (vm.js:316:10)
at Module._compile (internal/modules/cjs/loader.js:670:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
at startup (internal/bootstrap/node.js:303:19)
npm ERR! Test failed. See above for more details.

Process finished with exit code 1`

By the way, I tried the source code on 2 machines, where:
   
   - Windows 10
   - Node.JS 11.0.0
   - NPM 6.4.1

**Comment by Alek5andr** [comment]
> it seems to be your operating system is not loading the modules. It seems to be NPM module loader is not able to load. try NPM version 6.10 or 8.10 etc. and let me know

@amiya-pattnaik,
I have tried switching NPM (6.4.1) to the following versions:

- 6.1.0
- 6.10.1

Previously I also tried with Node.JS 8.12.0 and NPM 6.4.1.
The same outcome - the error appears.

You have very attractive example for UI testing that I would like to run and scrutinize its work.
However, it does not build in my case. So I have to continue with composing my own solution with WebdriverIO v5, which runs fine.
If you will find any solutions or tips to the error, please let me know, @amiya-pattnaik.

**Comment by vinodtestautomation** [comment]
@amiya-pattnaik , @Alek5andr 
I am also facing same issue.
NPM - 6.13.4 
node - 12.14.1

Error log:


 webdriveio@1.0.0 test c:\Users\admin\Desktop\WebdriveIO
> node ./node_modules/.bin/wdio ./wdio.conf.js

c:\Users\admin\Desktop\WebdriveIO\node_modules\.bin\wdio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at Module._compile (internal/modules/cjs/loader.js:891:18)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:811:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriveio@1.0.0 test: `node ./node_modules/.bin/wdio ./wdio.conf.js`
npm ERR! Exit status 1
npm ERR!

**Comment by vinodtestautomation** [comment]
> > it seems to be your operating system is not loading the modules. It seems to be NPM module loader is not able to load. try NPM version 6.10 or 8.10 etc. and let me know
> 
> @amiya-pattnaik,
> I have tried switching NPM (6.4.1) to the following versions:
> 
> * 6.1.0
> * 6.10.1
> 
> Previously I also tried with Node.JS 8.12.0 and NPM 6.4.1.
> The same outcome - the error appears.
> 
> You have very attractive example for UI testing that I would like to run and scrutinize its work.
> However, it does not build in my case. So I have to continue with composing my own solution with WebdriverIO v5, which runs fine.
> If you will find any solutions or tips to the error, please let me know, @amiya-pattnaik.

Did you got any solution !

**Comment by amiya-pattnaik** [comment]
The issue is not on the boilerplate project but rather specific to a particular version of Node.js in a combination with windows OS.
What version of Node are you using? You mentioned that you have your own solution with WebdriverIO v5. Is it working with the same Node version and failing with my boilerplate project ?
Thanks,Amiya 

    On Saturday, 14 March, 2020, 09:30:07 am GMT-5, vinodtestautomation <notifications@github.com> wrote:  
 
 




it seems to be your operating system is not loading the modules. It seems to be NPM module loader is not able to load. try NPM version 6.10 or 8.10 etc. and let me know


@amiya-pattnaik,
I have tried switching NPM (6.4.1) to the following versions:
   
   - 6.1.0
   - 6.10.1

Previously I also tried with Node.JS 8.12.0 and NPM 6.4.1.
The same outcome - the error appears.

You have very attractive example for UI testing that I would like to run and scrutinize its work.
However, it does not build in my case. So I have to continue with composing my own solution with WebdriverIO v5, which runs fine.
If you will find any solutions or tips to the error, please let me know, @amiya-pattnaik.


Did you got any solution !
