### ISSUE TITLE
Tests not running.

### ISSUE THREAD

**Issue by mattpaulwilliamson** [amiya-pattnaik/webdriverIO-with-jasmineBDD#4]
Hi wondering if you could help me out I have set my mac up as your instructions say and my tests get no feedback or seem to run.

![Screen Shot 2019-05-03 at 09 21 04](https://user-images.githubusercontent.com/1433898/57126478-fed51980-6d84-11e9-906f-353abbcfc2c2.png)

I know it is possibly related to my machine the issue but wondering if you had seen this before?

Thanks
Matt

**Comment by amiya-pattnaik** [comment]
please clone the project again and try. this project has been used by n-number of people and nobody reported this kind of issue and I also tried in another MAC and Windows and test is running fine.
Please try again and let me know

**Comment by amiya-pattnaik** [comment]
Has selenium server up and running? and Is your Chrome browser invoked?
If invoked and not able to load the URL etc. then it seems to be incompatible browser version Vs browser driver version. Please check and let me know

**Comment by amiya-pattnaik** [comment]
closing this as no updates from mattpaulwilliamson
