### ISSUE TITLE
Unable to upgrade chrome driver version to run tests on latest chrome browser

### ISSUE THREAD

**Issue by lemoncypress** [amiya-pattnaik/webdriverIO-with-jasmineBDD#6]
We are not sure where to make changes to update the chrome driver. We have tried - 

1. Adding a dependency for "wdio-chromedriver-service": "^6.0.0" > we saw an error

2. Adding a dependency for "chromedriver": "84.0.1" > we saw an error (refer error screenshot)
<img width="1365" alt="Screen Shot 2020-08-18 at 11 30 52" src="https://user-images.githubusercontent.com/48631861/90671663-055dfd80-e223-11ea-82e7-63b2e5fc8271.png">

3. Updating
seleniumInstallArgs: {
    version: '3.5.3'
  },
  seleniumArgs: {
    version: '3.5.3'
  }
from 3.4.0 to 3.5.3 (which we read from the docker config) > but it didn't work

4. Adding a config file called .npmrc, install the chromedriver and force the download when the execution starts > no luck!!

We are running out of ideas. Please guide us on how to go about this. This issue started when the remote server we run tests on got upgraded to a newer version automatically.

**Comment by amiya-pattnaik** [comment]
Check your proxy. it might be issue with your proxy.
Also take this latest wdio-v6 code and try it.
